remote_theme: thuhcsi/slate
title: Towards Multi-Scale Speaking Style Modelling with Hierarchical Context Information for Mandarin Speech Synthesis
description: Submitted to Interspeech 2022.
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
